name = "g_kod"
version = "0.0.1"
target = "javascript"
dev-dependencies = { gleeunit = ">= 1.2.0 and < 2.0.0"}

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = "~> 0.30"
sprinkle = ">= 1.0.1 and < 2.0.0"
